#!/usr/bin/env python3
"""
swift_pc_source_viewer.py

Create a PDF packet of zoomed-in images of a point source from
Swift XRT PC-mode cleaned event files. Uses position information
from _pileup.txt files generated by swift_xrt_king_profile.py.

Usage:
    python swift_pc_source_viewer.py
    python swift_pc_source_viewer.py --dimension 60arcsec
    python swift_pc_source_viewer.py --dimension 80px --sosta
    python swift_pc_source_viewer.py --radius 12

Required:
    _pileup.txt files (from swift_xrt_king_profile.py) must exist
    in the OBSID directories.

Optional arguments:
    --dimension   Image size, e.g. '100px' or '60arcsec' (default: 100px)
    --radius      Circle overlay radius in arcsec (default: 8)
    --sosta       Also read xrtcentroid positions from
                  source_extraction_OBSID.txt files
    --pdf         Output PDF filename (default: source_images.pdf)

Requirements:
    astropy, matplotlib, numpy
"""

import os
import sys
import glob
import re
import argparse
import numpy as np

try:
    from astropy.io import fits
except ImportError:
    print("ERROR: astropy is required. Install with: pip install astropy")
    sys.exit(1)

try:
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    from matplotlib.backends.backend_pdf import PdfPages
    from matplotlib.patches import Circle
    from matplotlib.colors import PowerNorm
    import matplotlib.lines as mlines
except ImportError:
    print("ERROR: matplotlib is required.")
    sys.exit(1)


# ---------------------------------------------------------------
# Parse _pileup.txt files
# ---------------------------------------------------------------

def read_pileup_info(pileup_file):
    """
    Read source position and plate scale from a _pileup.txt file.

    Returns dict with keys: xc, yc, ra, dec, plate_scale,
    pileup_radius, override_radius (any may be None).
    """
    info = {
        'xc': None, 'yc': None,
        'ra': None, 'dec': None,
        'plate_scale': None,
        'pileup_radius': None,
        'override_radius': None,
    }

    with open(pileup_file, 'r') as f:
        for line in f:
            line = line.strip()

            # Centroid position (pix)
            m = re.search(r'Centroid position \(pix\):\s*X=([\d.]+)\s+Y=([\d.]+)', line)
            if m:
                info['xc'] = float(m.group(1))
                info['yc'] = float(m.group(2))

            # Source position RA/Dec
            m = re.search(r'Source position \(input\):\s*RA=([\d.]+)\s+Dec=([\d.-]+)', line)
            if m:
                info['ra'] = float(m.group(1))
                info['dec'] = float(m.group(2))

            # Plate scale
            m = re.search(r'Plate scale:\s*([\d.]+)\s*arcsec/pixel', line)
            if m:
                info['plate_scale'] = float(m.group(1))

            # Pileup radius
            m = re.match(r'pileup_radius_arcsec\s*=\s*([\d.]+)', line)
            if m:
                info['pileup_radius'] = float(m.group(1))

            # Override radius
            m = re.match(r'override_radius_arcsec\s*=\s*([\d.]+)', line)
            if m:
                info['override_radius'] = float(m.group(1))

    return info


# ---------------------------------------------------------------
# Parse source_extraction_OBSID.txt files (SOSTA/xrtcentroid)
# ---------------------------------------------------------------

def read_sosta_info(sosta_file):
    """
    Read xrtcentroid pixel position from a source_extraction file.

    Returns dict with keys: xc_xrt, yc_xrt, ra_xrt, dec_xrt
    (any may be None).
    """
    info = {
        'xc_xrt': None, 'yc_xrt': None,
        'ra_xrt': None, 'dec_xrt': None,
    }

    with open(sosta_file, 'r') as f:
        in_xrtcentroid = False
        for line in f:
            line_stripped = line.strip()

            if 'xrtcentroid Results' in line_stripped:
                in_xrtcentroid = True
                continue

            if in_xrtcentroid:
                # RA (deg)
                m = re.match(r'RA\s+\(deg\)\s*:\s*([\d.]+)', line_stripped)
                if m:
                    info['ra_xrt'] = float(m.group(1))

                # Dec (deg)
                m = re.match(r'Dec\s+\(deg\)\s*:\s*([\d.-]+)', line_stripped)
                if m:
                    info['dec_xrt'] = float(m.group(1))

                # Pixel Position
                m = re.match(r'Pixel Position\s*:\s*\(([\d.]+),\s*([\d.]+)\)',
                             line_stripped)
                if m:
                    info['xc_xrt'] = float(m.group(1))
                    info['yc_xrt'] = float(m.group(2))

                # Stop after the section ends
                if line_stripped.startswith('===') and info['xc_xrt']:
                    break

    return info


# ---------------------------------------------------------------
# Parse dimension argument
# ---------------------------------------------------------------

def parse_dimension(dim_str, plate_scale):
    """
    Parse a dimension string like '100px' or '60arcsec'.
    Returns dimension in pixels.
    """
    dim_str = dim_str.strip().lower()

    m = re.match(r'([\d.]+)\s*arcsec', dim_str)
    if m:
        arcsec = float(m.group(1))
        return int(np.ceil(arcsec / plate_scale))

    m = re.match(r'([\d.]+)\s*px', dim_str)
    if m:
        return int(float(m.group(1)))

    # Try bare number as pixels
    try:
        return int(float(dim_str))
    except ValueError:
        print(f"WARNING: Could not parse dimension '{dim_str}', "
              f"using 100px")
        return 100


# ---------------------------------------------------------------
# Create source image from event file
# ---------------------------------------------------------------

def make_source_image(filepath, xc, yc, half_size):
    """
    Bin events from a FITS event file into a 2D image centered
    on (xc, yc) with extent +/- half_size pixels.

    Returns:
        image   : 2D numpy array (counts per pixel)
        extent  : (xmin, xmax, ymin, ymax) in pixel coordinates
    """
    with fits.open(filepath) as hdul:
        evt_ext = None
        for i, ext in enumerate(hdul):
            if ext.name == 'EVENTS':
                evt_ext = i
                break
        if evt_ext is None:
            evt_ext = 1

        data = hdul[evt_ext].data
        x_events = data['X'].astype(float)
        y_events = data['Y'].astype(float)

    # Define pixel boundaries for the cutout
    x_lo = int(np.floor(xc - half_size))
    x_hi = int(np.ceil(xc + half_size))
    y_lo = int(np.floor(yc - half_size))
    y_hi = int(np.ceil(yc + half_size))

    n_pix = x_hi - x_lo

    # Bin events into image
    mask = ((x_events >= x_lo) & (x_events < x_hi) &
            (y_events >= y_lo) & (y_events < y_hi))

    image, _, _ = np.histogram2d(
        y_events[mask], x_events[mask],
        bins=[np.arange(y_lo, y_hi + 1),
              np.arange(x_lo, x_hi + 1)])

    extent = (x_lo, x_hi, y_lo, y_hi)
    return image, extent


# ---------------------------------------------------------------
# Plot source image
# ---------------------------------------------------------------

def make_source_plot(evt_stem, image, extent, xc, yc, plate_scale,
                     circle_radius_arcsec, pileup_info,
                     sosta_info=None):
    """
    Create a zoomed-in image of the source with overlays.

    Returns:
        fig : matplotlib figure
    """
    fig, ax = plt.subplots(1, 1, figsize=(8, 8))

    x_lo, x_hi, y_lo, y_hi = extent

    # Determine stretch from the zoomed region
    vmin = 0
    vmax = max(np.max(image), 1)

    ax.imshow(image, origin='lower', cmap='viridis',
              extent=[x_lo, x_hi, y_lo, y_hi],
              interpolation='nearest',
              norm=PowerNorm(gamma=0.5, vmin=0, vmax=vmax),
              aspect='equal')

    # Circle and X at centroid position (magenta)
    r_pix = circle_radius_arcsec / plate_scale
    circle = Circle((xc, yc), r_pix, fill=False, edgecolor='magenta',
                    linewidth=1.5, linestyle='-', label='Centroid')
    ax.add_patch(circle)
    ax.plot(xc, yc, 'x', color='magenta', markersize=10,
            markeredgewidth=2, zorder=5)

    # If pileup or override radius available, show those too
    pileup_r = pileup_info.get('pileup_radius')
    override_r = pileup_info.get('override_radius')

    if pileup_r is not None:
        r_pu_pix = pileup_r / plate_scale
        c_pu = Circle((xc, yc), r_pu_pix, fill=False,
                       edgecolor='red', linewidth=1.2,
                       linestyle='--', label=f'Pile-up: {pileup_r:.1f}"')
        ax.add_patch(c_pu)

    if override_r is not None:
        r_ov_pix = override_r / plate_scale
        c_ov = Circle((xc, yc), r_ov_pix, fill=False,
                       edgecolor='purple', linewidth=1.2,
                       linestyle='--',
                       label=f'Override: {override_r:.1f}"')
        ax.add_patch(c_ov)

    # SOSTA/xrtcentroid position (dark orange)
    if sosta_info and sosta_info.get('xc_xrt') is not None:
        xc_xrt = sosta_info['xc_xrt']
        yc_xrt = sosta_info['yc_xrt']
        circle_xrt = Circle((xc_xrt, yc_xrt), r_pix, fill=False,
                             edgecolor='darkorange', linewidth=1.5,
                             linestyle='-', label='xrtcentroid')
        ax.add_patch(circle_xrt)
        ax.plot(xc_xrt, yc_xrt, 'x', color='darkorange',
                markersize=10, markeredgewidth=2, zorder=5)

    # Build legend with custom handles
    handles = []
    handles.append(mlines.Line2D([], [], color='magenta', marker='x',
                   linestyle='-', markersize=8, markeredgewidth=2,
                   label=f'Centroid ({circle_radius_arcsec:.0f}" circle)'))
    if sosta_info and sosta_info.get('xc_xrt') is not None:
        handles.append(mlines.Line2D([], [], color='darkorange',
                       marker='x', linestyle='-', markersize=8,
                       markeredgewidth=2,
                       label=f'xrtcentroid ({circle_radius_arcsec:.0f}" circle)'))
    if pileup_r is not None:
        handles.append(mlines.Line2D([], [], color='red',
                       linestyle='--', label=f'Pile-up: {pileup_r:.1f}"'))
    if override_r is not None:
        handles.append(mlines.Line2D([], [], color='purple',
                       linestyle='--',
                       label=f'Override: {override_r:.1f}"'))
    ax.legend(handles=handles, loc='upper left', fontsize=9,
              facecolor='black', edgecolor='white',
              labelcolor='white', framealpha=0.7)

    # Axis labels in pixels
    ax.set_xlabel('X (pixels)')
    ax.set_ylabel('Y (pixels)')

    # Add arcsec scale bar
    scale_len_arcsec = 10.0
    scale_len_pix = scale_len_arcsec / plate_scale
    bar_x = x_lo + 0.05 * (x_hi - x_lo)
    bar_y = y_lo + 0.05 * (y_hi - y_lo)
    ax.plot([bar_x, bar_x + scale_len_pix], [bar_y, bar_y],
            color='white', linewidth=3)
    ax.text(bar_x + scale_len_pix / 2, bar_y + 1.5,
            f'{scale_len_arcsec:.0f}"', color='white', fontsize=10,
            ha='center', va='bottom', fontweight='bold')

    ax.set_title(evt_stem, fontsize=12, color='white')

    # Dark background styling
    ax.set_facecolor('black')
    fig.patch.set_facecolor('black')
    ax.tick_params(colors='white')
    ax.xaxis.label.set_color('white')
    ax.yaxis.label.set_color('white')
    for spine in ax.spines.values():
        spine.set_edgecolor('white')

    return fig


# ---------------------------------------------------------------
# Main
# ---------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description='Create zoomed-in source images from Swift XRT '
                    'PC-mode event files.')
    parser.add_argument('--dimension', type=str, default='100px',
                        help='Image size, e.g. "100px" or "60arcsec" '
                             '(default: 100px)')
    parser.add_argument('--radius', type=float, default=8.0,
                        help='Circle overlay radius in arcsec '
                             '(default: 8)')
    parser.add_argument('--sosta', action='store_true',
                        help='Also read xrtcentroid positions from '
                             'source_extraction_OBSID.txt files')
    parser.add_argument('--pdf', type=str, default='source_images.pdf',
                        help='Output PDF filename '
                             '(default: source_images.pdf)')
    args = parser.parse_args()

    script_dir = os.getcwd()

    # Find OBSID directories
    obsid_pattern = re.compile(r'^\d{8,11}$')
    obsid_dirs = sorted([
        d for d in os.listdir(script_dir)
        if os.path.isdir(os.path.join(script_dir, d))
        and obsid_pattern.match(d)
    ])

    if not obsid_dirs:
        print("No OBSID directories found.")
        sys.exit(1)

    print(f"Found {len(obsid_dirs)} OBSID directories.")
    print(f"Image dimension: {args.dimension}")
    print(f"Circle radius: {args.radius} arcsec")
    if args.sosta:
        print("SOSTA/xrtcentroid overlay: enabled")

    all_figs = []

    for obsid in obsid_dirs:
        obsid_path = os.path.join(script_dir, obsid)

        # Find PC-mode cleaned event files (exclude slew)
        pc_files = glob.glob(os.path.join(obsid_path, '**',
                                           '*xpc*_cl.evt'),
                             recursive=True)
        pc_files += glob.glob(os.path.join(obsid_path, '**',
                                           '*xpc*_cl.evt.gz'),
                              recursive=True)
        pc_files = [f for f in pc_files
                    if 'sl_cl' not in os.path.basename(f).lower()]

        if not pc_files:
            continue

        # Load SOSTA file for this OBSID if requested
        sosta_info = None
        if args.sosta:
            sosta_file = os.path.join(
                obsid_path,
                f'source_extraction_{obsid}.txt')
            if os.path.exists(sosta_file):
                sosta_info = read_sosta_info(sosta_file)
                if sosta_info.get('xc_xrt') is not None:
                    print(f"  OBSID {obsid}: xrtcentroid at "
                          f"({sosta_info['xc_xrt']:.2f}, "
                          f"{sosta_info['yc_xrt']:.2f})")
            else:
                print(f"  OBSID {obsid}: no source_extraction "
                      f"file found.")

        for pc_file in pc_files:
            evt_stem = os.path.basename(pc_file).replace(
                '_cl.evt.gz', '').replace('_cl.evt', '')

            # Find corresponding _pileup.txt
            pileup_file = os.path.join(obsid_path,
                                        f'{evt_stem}_pileup.txt')
            if not os.path.exists(pileup_file):
                print(f"  {evt_stem}: no _pileup.txt found, "
                      f"skipping.")
                continue

            pileup_info = read_pileup_info(pileup_file)

            if pileup_info['xc'] is None or pileup_info['yc'] is None:
                print(f"  {evt_stem}: no centroid in _pileup.txt, "
                      f"skipping.")
                continue

            xc = pileup_info['xc']
            yc = pileup_info['yc']
            plate_scale = pileup_info.get('plate_scale', 2.36)

            # Parse dimension
            half_size = parse_dimension(args.dimension,
                                         plate_scale) / 2.0

            print(f"  {evt_stem}: center=({xc:.1f}, {yc:.1f}), "
                  f"cutout={2*half_size:.0f}px")

            # Create image
            try:
                image, extent = make_source_image(
                    pc_file, xc, yc, half_size)
            except Exception as e:
                print(f"    ERROR reading events: {e}")
                continue

            # Create plot
            fig = make_source_plot(
                evt_stem, image, extent, xc, yc, plate_scale,
                args.radius, pileup_info, sosta_info)

            # Save individual PNG
            png_path = os.path.join(obsid_path,
                                     f'{evt_stem}_source.png')
            fig.savefig(png_path, dpi=150, bbox_inches='tight',
                        facecolor='black')
            print(f"    Saved: {png_path}")

            all_figs.append(fig)

    # Collate into PDF
    if all_figs:
        pdf_path = os.path.join(script_dir, args.pdf)
        print(f"\nCollating {len(all_figs)} images into {pdf_path}")
        with PdfPages(pdf_path) as pdf:
            for fig in all_figs:
                pdf.savefig(fig, dpi=150, bbox_inches='tight',
                            facecolor='black')
                plt.close(fig)
        print(f"PDF saved: {pdf_path}")
    else:
        print("\nNo images were generated. Make sure _pileup.txt "
              "files exist (run swift_xrt_king_profile.py first).")


if __name__ == '__main__':
    main()
